
# ==============================================================
# 5️⃣ close-stale.yml — Auto Close Inactive Issues
# ==============================================================
name: Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been inactive for 30 days and will close soon. Comment to keep it open."
          close-issue-message: "Closed due to inactivity. Feel free to reopen if needed."
